language: python
python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8
env:
  matrix:
  - DEP_VERSIONS="oldest"  # Approximately the versions available in the last LTS release of Ubuntu, currently 18.04 LTS.
  - DEP_VERSIONS="latest"
  - DEP_VERSIONS="master"  # Run against SymPy master.
before_install:
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge  # conda-forge has top precedent
  - conda update -q conda
install:
  - sudo apt-get install phantomjs
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION
  - source activate test-env
  # NOTE : There is a bug in SymPy 1.1.1 that prevents the jupyter_sphinx
  # examples from building, so don't install jupyter_sphinx in oldest so it is
  # skipped.
  # NOTE : SymPy's master branch will no longer install with Python 2.7. The
  # last supported version is SymPy 1.5.
  # NOTE : matplotlib dropped Python 2.7 in version 3.0
  # NOTE : numpydoc dropped Python 2.7 in version 1.0
  # NOTE : scipy dropped Python 2.7 in version 1.3
  # NOTE : sphinx dropped Python 2.7 in version 2.0
  - if [[ $DEP_VERSIONS == "oldest" ]] && [[ $TRAVIS_PYTHON_VERSION == 3.* ]]; then
      conda install numpy=1.16.5 scipy=1.3.3 sympy=1.5.1 cython=0.29.14 theano=1.0.4 pip coverage nose flake8 matplotlib-base sphinx numpydoc;
    elif [[ $DEP_VERSIONS == "oldest" ]]; then
      conda install numpy=1.16.5 "scipy<1.3" sympy=1.5.1 cython=0.29.14 theano=1.0.4 pip coverage nose flake8 "matplotlib-base<3" "sphinx<2" "numpydoc<1";
    elif [[ $DEP_VERSIONS == "latest" ]] && [[ $TRAVIS_PYTHON_VERSION == 3.* ]]; then
      conda install numpy scipy sympy cython theano pythreejs pip coverage nose flake8 matplotlib sphinx numpydoc jupyter_sphinx;
    elif [[ $DEP_VERSIONS == "latest" ]]; then
      conda install "numpy<1.17" "scipy<1.3" "sympy<1.6" cython theano pip coverage nose flake8 "matplotlib-base<3" "sphinx<2" "numpydoc<1";
    elif [[ $DEP_VERSIONS == "master" ]] && [[ $TRAVIS_PYTHON_VERSION == 3.* ]]; then
      conda install numpy scipy mpmath fastcache cython theano pythreejs pip coverage nose flake8 matplotlib sphinx numpydoc jupyter_sphinx;
      pip install https://github.com/sympy/sympy/archive/master.zip;
    elif [[ $DEP_VERSIONS == "master" ]]; then
      conda install "sympy<1.6" "numpy<1.17" "scipy<1.3" cython theano pip coverage nose flake8 "matplotlib-base<3" "sphinx<2" "numpydoc<1";
    fi
before_script:
  - conda info
  - conda list
  - pip --version
  - pip freeze
script:
  # The THEANO_FLAGS are necessary for compilation on Travis CI.
  - THEANO_FLAGS='gcc.cxxflags="-march=core2"' nosetests -v --with-coverage --cover-package=pydy
  # JS tests
  - cd pydy/viz/static/js/tests && phantomjs run-jasmine.js SpecRunner.html
  - cd -  # It should not be combined with above command
  # Check Python and Javascript syntax (trailing whitespaces/newlines, unused imports).
  - (flake8 --select W1,W2,W3 --exclude booger . &&
    flake8 --select F401 --exclude booger,__init__.py,conf.py . &&
    flake8 --select W2,W3 --filename='*.js' examples/ pydy/viz/static/js/dyviz/) ||
    (echo "Please run a linter and fix errors, e.g. pylint, flake8, pep8, etc."; false)
  # Make sure the docs build (including the examples).
  - cd docs && make html && cd ..
  # Make sure the library installs.
  - python setup.py install
  # Run benchmark
  - python bin/benchmark_pydy_code_gen.py 1 10
