environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"

  matrix:
    - PYTHON: "C:\\Miniconda-x64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      CONDA_PY: "27"

    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      CONDA_PY: "36"

    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
      CONDA_PY: "37"

    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "64"
      CONDA_PY: "38"

install:
  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""

  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""

  # This upates conda and installs the necessary packages.
  # TODO : The latest pythreejs fails on Python 2.7, so it has been removed.
  # Need to drop PyDy 2.7 support or adjust this test.
  - "%PYTHON%\\Scripts\\conda.exe clean --yes --all"
  - "%PYTHON%\\Scripts\\conda.exe update --yes conda"
  - "%PYTHON%\\Scripts\\conda.exe update -y --all"
  - "%PYTHON%\\Scripts\\conda.exe config --prepend channels conda-forge"
  - '%PYTHON%\\Scripts\\conda.exe install --yes numpy scipy sympy cython pywin32 nose coverage'
  - "%PYTHON%\\Scripts\\conda.exe update -y --all"
  - "%PYTHON%\\Scripts\\conda.exe info"
  - "%PYTHON%\\Scripts\\conda.exe list"

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart the
  # parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

build: false

test_script:
  - "%CMD_IN_ENV% nosetests -v --with-coverage --cover-package=pydy"
